---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: msgpostgres
  name: msgpostgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msgpostgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: msgpostgres
    spec:
      containers:
      - name: msgpostgres
        image: imauld/msgpostgres:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: msgpostgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: msgpostgres
